-- MySQL Script generated by MySQL Workbench
-- Thu Jan 28 18:54:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Student
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Student
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Student` DEFAULT CHARACTER SET utf8 ;
USE `Student` ;

-- -----------------------------------------------------
-- Table `Student`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student`.`Groups` (
  `idGroups` INT NOT NULL AUTO_INCREMENT,
  `group` VARCHAR(45) NULL,
  PRIMARY KEY (`idGroups`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student`.`Students` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `name_stud` VARCHAR(45) NULL,
  `idGroup` INT NULL,
  `year_admis` INT NULL,
  INDEX `group_idx` (`idGroup` ASC) VISIBLE,
  PRIMARY KEY (`idStudent`),
  CONSTRAINT `group`
    FOREIGN KEY (`idGroup`)
    REFERENCES `Student`.`Groups` (`idGroups`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`.`Cathedras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student`.`Cathedras` (
  `idCathedra` INT NOT NULL AUTO_INCREMENT,
  `name_cathedra` VARCHAR(45) NULL,
  `chief` VARCHAR(45) NULL,
  PRIMARY KEY (`idCathedra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`.`Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student`.`Teachers` (
  `idTeachers` INT NOT NULL AUTO_INCREMENT,
  `name_teacher` VARCHAR(45) NULL,
  `cathedra` INT NULL,
  PRIMARY KEY (`idTeachers`),
  INDEX `cathedras_idx` (`cathedra` ASC) VISIBLE,
  CONSTRAINT `cathedras`
    FOREIGN KEY (`cathedra`)
    REFERENCES `Student`.`Cathedras` (`idCathedra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`.`Lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student`.`Lessons` (
  `idLessons` INT NOT NULL AUTO_INCREMENT,
  `name_lesson` VARCHAR(45) NULL,
  `teacher` INT NULL,
  `semester` INT NULL,
  `year` INT NULL,
  PRIMARY KEY (`idLessons`),
  INDEX `teacher_idx` (`teacher` ASC) VISIBLE,
  CONSTRAINT `teacher`
    FOREIGN KEY (`teacher`)
    REFERENCES `Student`.`Teachers` (`idTeachers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`.`Points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student`.`Points` (
  `idPoint` INT NOT NULL AUTO_INCREMENT,
  `lesson` INT NULL,
  `student` INT NULL,
  `point` INT NULL,
  PRIMARY KEY (`idPoint`),
  INDEX `student_idx` (`student` ASC) VISIBLE,
  INDEX `lessons_idx` (`lesson` ASC) VISIBLE,
  CONSTRAINT `student`
    FOREIGN KEY (`student`)
    REFERENCES `Student`.`Students` (`idStudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `lessons`
    FOREIGN KEY (`lesson`)
    REFERENCES `Student`.`Lessons` (`idLessons`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
